version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  db-test:
    image: postgres:latest
    env_file:
      - ./.env.test.local
      - ./.env
    ports:
      - 5433:5432

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  data:
