name: ci
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:shiritori@localhost:5432/shiritori-test

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: shiritori
          POSTGRES_DB: shiritori-test

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install NPM dependencies 📦
        uses: bahmutov/npm-install@v1

      - name: Install and run Cypress tests 🌲
        uses: cypress-io/github-action@v2
        with:
          command: yarn run test:e2e

  unit:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:shiritori@localhost:5432/shiritori-test

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: shiritori
          POSTGRES_DB: shiritori-test

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # we are only interested in installing and caching dependencies,
      # without installing the Cypress binary
      - name: Install NPM dependencies 📦
        uses: bahmutov/npm-install@v1
        env:
          # we do not need to install Cypress itself
          # as we do not plan to run tests
          CYPRESS_INSTALL_BINARY: 0

      - name: Lint
        run: yarn lint

      - name: Prisma Migrate
        run: yarn migrate

      - name: Run Jest tests 🧪
        run: yarn test:jest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
